name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on a different branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Set up miniconda
      run: |
        sudo apt-get update
        sudo apt-get -y install wget
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm ~/miniconda3/miniconda.sh
        conda install -c conda-forge vispy
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        steps:
    ## Following vispy's setup 
    - name: Install OpenGL
      run: |
        sudo apt-get update
        sudo apt-get -y install x11-utils libxcb-cursor0
    - name: Start xvfb daemon
      run: |
        export DISPLAY=:99.0
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
        sleep 5
    - name: Check OpenGL
      run: |
        export DISPLAY=:99.0
        glxinfo
    - name: Check Display Information
      run: |
        export DISPLAY=:99.0
        xdpyinfo
    ##
    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz
    - name: Install dependencies
      run: |
        pip install sphinx pydata-sphinx-theme matplotlib sphinx-gallery sphinxcontrib-bibtex sphinx-copybutton jupyter-sphinx setuptools sphinx-design
        conda install -c conda-forge vispy
        pip install pillow PyQt6 jupyter_rfb triangle 
        python -m pip install --upgrade pip
        pip install -e .[all]  
    - name: Check VisPy Backend
      run: |
        export DISPLAY=:99.0
        python -c "import vispy; print(vispy.sys_info())"
    - name: Build documentation
      run: |
        export DISPLAY=:99.0
        sphinx-build -b html ./docs/source ./docs/build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
