name: Deploy Sphinx Documentation
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        auto-update-conda: true
        activate-environment: sphinx-env
        environment-file: null
        auto-activate-base: false

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Qt and OpenGL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglu1-mesa-dev \
          libgl1-mesa-dev \
          libxi-dev \
          libglfw3-dev \
          libgles2-mesa-dev \
          libsdl2-2.0-0 \
          mesa-utils \
          x11-utils \
          xvfb \
          libxcb-cursor0 \
          libxcb-xinerama0 \
          libxcb-randr0 \
          libxcb-xtest0 \
          libxcb-shape0 \
          libxcb-xkb1 \
          libxkbcommon-x11-0 \
          libdbus-1-3 \
          '^libxcb.*-dev' \
          libxkbcommon-dev \
          libxcb-xinerama0-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-render-util0-dev

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1400x900x24 -ac +extension GLX +render &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "QT_DEBUG_PLUGINS=1" >> $GITHUB_ENV

    - name: Install Graphviz
      run: sudo apt-get install -y graphviz

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        # Install Qt first
        pip install PyQt6
        # Then install vispy
        conda install -c conda-forge vispy
        # Then other dependencies
        pip install \
          sphinx \
          pydata-sphinx-theme \
          matplotlib \
          sphinx-gallery \
          sphinxcontrib-bibtex \
          sphinx-copybutton \
          jupyter-sphinx \
          setuptools \
          sphinx-design \
          pillow \
          jupyter_rfb \
          triangle

    - name: Install package
      shell: bash -l {0}
      run: pip install -e .[all]

    - name: Check Qt and Display
      shell: bash -l {0}
      run: |
        echo "DISPLAY=$DISPLAY"
        echo "Qt plugins directory:"
        python -c "from PyQt6.QtCore import QLibraryInfo; print(QLibraryInfo.path(QLibraryInfo.LibraryPath.PluginsPath))"
        ls -l $(python -c "from PyQt6.QtCore import QLibraryInfo; print(QLibraryInfo.path(QLibraryInfo.LibraryPath.PluginsPath))")

    - name: Verify VisPy setup
      shell: bash -l {0}
      run: |
        python -c "import vispy; print(vispy.sys_info())"

    - name: Build documentation
      shell: bash -l {0}
      run: sphinx-build -b html ./docs/source ./docs/build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build