name: Deploy Sphinx Documentation
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --login -e {0}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        auto-update-conda: true
        activate-environment: sphinx-env
        environment-file: null
        auto-activate-base: false

    - name: Prepare System Environment
      run: |
        # opengl system libraries
        sudo apt-get update
        sudo apt-get -y install \
          libglu1-mesa-dev \
          libgl1-mesa-dev \
          libxi-dev \
          libglfw3-dev \
          libgles2-mesa-dev \
          libsdl2-2.0-0 \
          mesa-utils \
          x11-utils \
          xvfb \
          libxcb* \
          libxkbcommon* \
          qt6-base-dev
        
        # Start xvfb daemon
        export DISPLAY=:99.0
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
        sleep 5
        
        # Create XDG runtime dir
        export XDG_RUNTIME_DIR=/tmp/runtime-runner
        mkdir -p $XDG_RUNTIME_DIR
        chmod 700 $XDG_RUNTIME_DIR
        echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> $GITHUB_ENV
        echo "DISPLAY=:99.0" >> $GITHUB_ENV

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        # Install PyQt6 first
        pip install PyQt6
        # Then install other dependencies
        pip install \
          sphinx \
          pydata-sphinx-theme \
          matplotlib \
          sphinx-gallery \
          sphinxcontrib-bibtex \
          sphinx-copybutton \
          jupyter-sphinx \
          setuptools \
          sphinx-design \
          pillow \
          jupyter_rfb \
          triangle
        # Install vispy last
        pip install vispy

    - name: Install package
      shell: bash -l {0}
      run: pip install -e .[all]

    - name: Verify System Setup
      shell: bash -l {0}
      run: |
        glxinfo
        xdpyinfo
        echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
        echo "DISPLAY=$DISPLAY"

    - name: Verify VisPy setup
      shell: bash -l {0}
      run: |
        python -c "
        import vispy
        print('VisPy imported successfully')
        print('Current backend:', vispy.app.use_app().backend_name)
        print('Available backends:', vispy.app.backends())
        print('\nSystem info:')
        print(vispy.sys_info())
        "

    - name: Build documentation
      shell: bash -l {0}
      run: sphinx-build -b html ./docs/source ./docs/build

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build